theme = "modus_operandi_tinted"

[editor]
true-color = true
mouse = true
line-number = "relative"

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = false

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]

[keys.insert]
C-space = "signature_help"

[keys.normal]
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
