########## Python ########## 
[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
roots = ["pyproject.toml", "setup.py", ".project", ".pydevproject", ".git"]

[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio" ]
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = false
extraPaths = ["~/container-packages"]

[language-server.ruff]
command = "ruff"
args = ["server"]
[language-server.ruff.config.settings]
args = ["--ignore", "E501, E402"]
[language-server.ruff.config.settings.lint]
select = ["W"]

########## Bash ########## 
[[language]]
name = "bash"
shebangs = ["sh", "bash", "bats"]
file-types = ["sh"]

########## TCL ########## 
[[language]]
name = "tcl"
shebangs = ["expect"]

########## C ########## 
[[language]]
name = "c"
language-servers = ["clangd"]

[language-server.clangd]
command = "clangd"
# args = ["--compile-commands-dir=build"]

########## Groovy ########## 
[[language]]
name = "groovy"
scope = "source.groovy"
file-types = ["groovy", "gradle", "Jenkinsfile", "nf"]
language-servers = ["groovyls"]

[language-server.groovyls]
command = "java"
args = ["-jar", "/home/anle/groovy-language-server/build/libs/groovy-language-server-all.jar"]
